"""Known secret paths: the deny rules for Claude Code's own permissions.

The plugin's hook finds secrets by content. These rules block files by name before any
hook runs: SSH keys, environment files, cloud and password-manager credentials, shell
history, browser profiles, and the commands that would print them. They live in the
user's Claude Code settings file, which a plugin cannot write on its own, so cguard
carries them as data and installs them on request.
"""
import json
import os
from pathlib import Path

SETTINGS_PATH = Path(os.environ.get("CGUARD_SETTINGS") or os.path.expanduser("~/.claude/settings.json"))

RULES = [
    # The original set: SSH keys, environment files, key formats, cloud and tool credentials, shell and database history, browser profiles, the env and printenv commands
    "Read(~/.ssh)",
    "Read(~/.ssh/**)",
    "Edit(~/.ssh)",
    "Edit(~/.ssh/**)",
    "Write(~/.ssh)",
    "Write(~/.ssh/**)",
    "Bash(*/.ssh*)",
    "Read(//**/.env)",
    "Read(//**/.env.local)",
    "Read(//**/.env.production)",
    "Read(//**/.env.*.local)",
    "Read(//**/.backup-env)",
    "Edit(//**/.env)",
    "Edit(//**/.env.local)",
    "Edit(//**/.env.production)",
    "Edit(//**/.env.*.local)",
    "Edit(//**/.backup-env)",
    "Write(//**/.env)",
    "Write(//**/.env.local)",
    "Write(//**/.env.production)",
    "Write(//**/.env.*.local)",
    "Write(//**/.backup-env)",
    # A reader with an environment file as its argument: the name right after the reader, after
    # other arguments, or at the end of a path. It ends the command, is followed by a space, or
    # continues as .env.local and the like. The earlier form *cat *.env* also matched os.environ
    # and process.env inside unrelated text, and refused a search for process.env or a commit
    # message naming the file.
    "Bash(*cat .env)",
    "Bash(*cat .env *)",
    "Bash(*cat .env.*)",
    "Bash(*cat * .env)",
    "Bash(*cat * .env *)",
    "Bash(*cat * .env.*)",
    "Bash(*cat */.env)",
    "Bash(*cat */.env *)",
    "Bash(*cat */.env.*)",
    "Bash(*bat .env)",
    "Bash(*bat .env *)",
    "Bash(*bat .env.*)",
    "Bash(*bat * .env)",
    "Bash(*bat * .env *)",
    "Bash(*bat * .env.*)",
    "Bash(*bat */.env)",
    "Bash(*bat */.env *)",
    "Bash(*bat */.env.*)",
    "Bash(*less .env)",
    "Bash(*less .env *)",
    "Bash(*less .env.*)",
    "Bash(*less * .env)",
    "Bash(*less * .env *)",
    "Bash(*less * .env.*)",
    "Bash(*less */.env)",
    "Bash(*less */.env *)",
    "Bash(*less */.env.*)",
    "Bash(*head .env)",
    "Bash(*head .env *)",
    "Bash(*head .env.*)",
    "Bash(*head * .env)",
    "Bash(*head * .env *)",
    "Bash(*head * .env.*)",
    "Bash(*head */.env)",
    "Bash(*head */.env *)",
    "Bash(*head */.env.*)",
    "Bash(*tail .env)",
    "Bash(*tail .env *)",
    "Bash(*tail .env.*)",
    "Bash(*tail * .env)",
    "Bash(*tail * .env *)",
    "Bash(*tail * .env.*)",
    "Bash(*tail */.env)",
    "Bash(*tail */.env *)",
    "Bash(*tail */.env.*)",
    "Bash(*grep .env)",
    "Bash(*grep .env *)",
    "Bash(*grep .env.*)",
    "Bash(*grep * .env)",
    "Bash(*grep * .env *)",
    "Bash(*grep * .env.*)",
    "Bash(*grep */.env)",
    "Bash(*grep */.env *)",
    "Bash(*grep */.env.*)",
    "Bash(*source .env)",
    "Bash(*source .env *)",
    "Bash(*source .env.*)",
    "Bash(*source ./.env)",
    "Bash(*source ./.env *)",
    "Bash(*source ./.env.*)",
    "Bash(*. .env)",
    "Bash(*. .env *)",
    "Bash(*. .env.*)",
    "Bash(*. ./.env)",
    "Bash(*. ./.env *)",
    "Bash(*. ./.env.*)",
    "Read(//**/*.pem)",
    "Read(//**/*.key)",
    "Read(//**/*.p12)",
    "Read(//**/*.pfx)",
    "Read(//**/*.kdbx)",
    "Read(//**/id_rsa*)",
    "Read(//**/id_ed25519*)",
    "Read(//**/*.tfstate)",
    "Read(//**/*.tfvars)",
    "Edit(//**/*.pem)",
    "Edit(//**/*.key)",
    "Edit(//**/*.p12)",
    "Edit(//**/*.pfx)",
    "Edit(//**/*.kdbx)",
    "Edit(//**/id_rsa*)",
    "Edit(//**/id_ed25519*)",
    "Edit(//**/*.tfstate)",
    "Edit(//**/*.tfvars)",
    "Write(//**/*.pem)",
    "Write(//**/*.key)",
    "Write(//**/*.p12)",
    "Write(//**/*.pfx)",
    "Write(//**/*.kdbx)",
    "Write(//**/id_rsa*)",
    "Write(//**/id_ed25519*)",
    "Write(//**/*.tfstate)",
    "Write(//**/*.tfvars)",
    "Read(~/.aws/**)",
    "Read(~/.azure/**)",
    "Read(~/.config/gcloud/**)",
    "Read(~/.config/hcloud/**)",
    "Read(~/.kube/**)",
    "Read(~/.gnupg/**)",
    "Read(~/.docker/config.json)",
    "Read(~/.netrc)",
    "Read(~/.git-credentials)",
    "Read(~/.password-store/**)",
    "Read(~/.config/Bitwarden CLI/**)",
    "Read(~/.config/rclone/**)",
    "Read(~/.config/sops/**)",
    "Read(~/.terraform.d/**)",
    "Read(~/.claude/.credentials.json)",
    "Edit(~/.aws/**)",
    "Edit(~/.azure/**)",
    "Edit(~/.config/gcloud/**)",
    "Edit(~/.config/hcloud/**)",
    "Edit(~/.kube/**)",
    "Edit(~/.gnupg/**)",
    "Edit(~/.docker/config.json)",
    "Edit(~/.netrc)",
    "Edit(~/.git-credentials)",
    "Edit(~/.password-store/**)",
    "Edit(~/.config/Bitwarden CLI/**)",
    "Edit(~/.config/rclone/**)",
    "Edit(~/.config/sops/**)",
    "Edit(~/.terraform.d/**)",
    "Edit(~/.claude/.credentials.json)",
    "Write(~/.aws/**)",
    "Write(~/.azure/**)",
    "Write(~/.config/gcloud/**)",
    "Write(~/.config/hcloud/**)",
    "Write(~/.kube/**)",
    "Write(~/.gnupg/**)",
    "Write(~/.docker/config.json)",
    "Write(~/.netrc)",
    "Write(~/.git-credentials)",
    "Write(~/.password-store/**)",
    "Write(~/.config/Bitwarden CLI/**)",
    "Write(~/.config/rclone/**)",
    "Write(~/.config/sops/**)",
    "Write(~/.terraform.d/**)",
    "Write(~/.claude/.credentials.json)",
    "Bash(*/.aws*)",
    "Bash(*/.azure*)",
    "Bash(*/.config/gcloud*)",
    "Bash(*/.config/hcloud*)",
    "Bash(*/.kube*)",
    "Bash(*/.gnupg*)",
    "Bash(*/.docker/config.json*)",
    "Bash(*/.netrc*)",
    "Bash(*/.git-credentials*)",
    "Bash(*/.password-store*)",
    "Bash(*/.credentials.json*)",
    "Read(~/.bash_history)",
    "Read(~/.zsh_history)",
    "Read(~/.local/share/fish/fish_history)",
    "Read(~/.python_history)",
    "Read(~/.psql_history)",
    "Read(~/.mysql_history)",
    "Bash(*/.bash_history*)",
    "Bash(*/.zsh_history*)",
    "Bash(*fish_history*)",
    "Bash(*/.psql_history*)",
    "Read(~/.mozilla/**)",
    "Read(~/.config/chromium/**)",
    "Read(~/.config/google-chrome/**)",
    "Read(~/.config/BraveSoftware/**)",
    "Bash(*/.mozilla*)",
    "Bash(*/.config/chromium*)",
    "Bash(*/.config/google-chrome*)",
    "Bash(*/.config/BraveSoftware*)",
    "Bash(printenv*)",
    "Bash(env)",
    "Read(//**/.ssh/**)",
    "Edit(//**/.ssh/**)",
    "Write(//**/.ssh/**)",
    "Read(//**/*.ppk)",
    "Edit(//**/*.ppk)",
    "Write(//**/*.ppk)",
    "Bash(*.ppk*)",

    # Developer tool credentials: GitHub CLI, package registries, database logins, hosting and cloud CLIs, AI tooling, tunnels and VPN, and key formats
    "Read(~/.config/gh/hosts.yml)",
    "Edit(~/.config/gh/hosts.yml)",
    "Write(~/.config/gh/hosts.yml)",
    "Read(~/.npmrc)",
    "Edit(~/.npmrc)",
    "Write(~/.npmrc)",
    "Read(//**/.npmrc)",
    "Edit(//**/.npmrc)",
    "Write(//**/.npmrc)",
    "Read(~/.yarnrc.yml)",
    "Edit(~/.yarnrc.yml)",
    "Write(~/.yarnrc.yml)",
    "Read(~/.pypirc)",
    "Edit(~/.pypirc)",
    "Write(~/.pypirc)",
    "Read(~/.cargo/credentials)",
    "Edit(~/.cargo/credentials)",
    "Write(~/.cargo/credentials)",
    "Read(~/.cargo/credentials.toml)",
    "Edit(~/.cargo/credentials.toml)",
    "Write(~/.cargo/credentials.toml)",
    "Read(~/.gem/credentials)",
    "Edit(~/.gem/credentials)",
    "Write(~/.gem/credentials)",
    "Read(~/.composer/auth.json)",
    "Edit(~/.composer/auth.json)",
    "Write(~/.composer/auth.json)",
    "Read(~/.m2/settings.xml)",
    "Edit(~/.m2/settings.xml)",
    "Write(~/.m2/settings.xml)",
    "Read(~/.gradle/gradle.properties)",
    "Edit(~/.gradle/gradle.properties)",
    "Write(~/.gradle/gradle.properties)",
    "Read(~/.nuget/NuGet/NuGet.Config)",
    "Edit(~/.nuget/NuGet/NuGet.Config)",
    "Write(~/.nuget/NuGet/NuGet.Config)",
    "Read(~/.pgpass)",
    "Edit(~/.pgpass)",
    "Write(~/.pgpass)",
    "Read(//**/.pgpass)",
    "Edit(//**/.pgpass)",
    "Write(//**/.pgpass)",
    "Read(~/.my.cnf)",
    "Edit(~/.my.cnf)",
    "Write(~/.my.cnf)",
    "Read(//**/.my.cnf)",
    "Edit(//**/.my.cnf)",
    "Write(//**/.my.cnf)",
    "Read(~/.databrickscfg)",
    "Edit(~/.databrickscfg)",
    "Write(~/.databrickscfg)",
    "Read(~/.config/vercel/**)",
    "Edit(~/.config/vercel/**)",
    "Write(~/.config/vercel/**)",
    "Read(~/.netlify/**)",
    "Edit(~/.netlify/**)",
    "Write(~/.netlify/**)",
    "Read(~/.fly/**)",
    "Edit(~/.fly/**)",
    "Write(~/.fly/**)",
    "Read(~/.config/railway/**)",
    "Edit(~/.config/railway/**)",
    "Write(~/.config/railway/**)",
    "Read(~/.config/doctl/**)",
    "Edit(~/.config/doctl/**)",
    "Write(~/.config/doctl/**)",
    "Read(~/.wrangler/**)",
    "Edit(~/.wrangler/**)",
    "Write(~/.wrangler/**)",
    "Read(~/.config/.wrangler/**)",
    "Edit(~/.config/.wrangler/**)",
    "Write(~/.config/.wrangler/**)",
    "Read(~/.pulumi/credentials.json)",
    "Edit(~/.pulumi/credentials.json)",
    "Write(~/.pulumi/credentials.json)",
    "Read(~/.vault-token)",
    "Edit(~/.vault-token)",
    "Write(~/.vault-token)",
    "Read(~/.config/doppler/**)",
    "Edit(~/.config/doppler/**)",
    "Write(~/.config/doppler/**)",
    "Read(~/.config/infisical/**)",
    "Edit(~/.config/infisical/**)",
    "Write(~/.config/infisical/**)",
    "Read(~/.cache/huggingface/token)",
    "Edit(~/.cache/huggingface/token)",
    "Write(~/.cache/huggingface/token)",
    "Read(~/.huggingface/token)",
    "Edit(~/.huggingface/token)",
    "Write(~/.huggingface/token)",
    "Read(~/.codex/auth.json)",
    "Edit(~/.codex/auth.json)",
    "Write(~/.codex/auth.json)",
    "Read(~/.config/openai/**)",
    "Edit(~/.config/openai/**)",
    "Write(~/.config/openai/**)",
    "Read(~/.openai/**)",
    "Edit(~/.openai/**)",
    "Write(~/.openai/**)",
    "Read(~/.gemini/**)",
    "Edit(~/.gemini/**)",
    "Write(~/.gemini/**)",
    "Read(~/.config/ngrok/ngrok.yml)",
    "Edit(~/.config/ngrok/ngrok.yml)",
    "Write(~/.config/ngrok/ngrok.yml)",
    "Read(~/.ngrok2/ngrok.yml)",
    "Edit(~/.ngrok2/ngrok.yml)",
    "Write(~/.ngrok2/ngrok.yml)",
    "Read(~/.tsh/**)",
    "Edit(~/.tsh/**)",
    "Write(~/.tsh/**)",
    "Read(~/.config/op/**)",
    "Edit(~/.config/op/**)",
    "Write(~/.config/op/**)",
    "Read(~/.config/1Password/**)",
    "Edit(~/.config/1Password/**)",
    "Write(~/.config/1Password/**)",
    "Read(//**/id_ecdsa*)",
    "Edit(//**/id_ecdsa*)",
    "Write(//**/id_ecdsa*)",
    "Read(//**/id_dsa*)",
    "Edit(//**/id_dsa*)",
    "Write(//**/id_dsa*)",
    "Read(//**/*.jks)",
    "Edit(//**/*.jks)",
    "Write(//**/*.jks)",
    "Read(//**/*.keystore)",
    "Edit(//**/*.keystore)",
    "Write(//**/*.keystore)",
    "Read(//**/*.p8)",
    "Edit(//**/*.p8)",
    "Write(//**/*.p8)",
    "Read(//**/*.asc)",
    "Edit(//**/*.asc)",
    "Write(//**/*.asc)",
    "Read(//**/*.gpg)",
    "Edit(//**/*.gpg)",
    "Write(//**/*.gpg)",
    "Read(//**/*.age)",
    "Edit(//**/*.age)",
    "Write(//**/*.age)",
    "Read(//**/*.ovpn)",
    "Edit(//**/*.ovpn)",
    "Write(//**/*.ovpn)",
    "Read(//**/.htpasswd)",
    "Edit(//**/.htpasswd)",
    "Write(//**/.htpasswd)",
    "Bash(*/.config/gh*)",
    "Bash(*/.npmrc*)",
    "Bash(*/.pypirc*)",
    "Bash(*/.pgpass*)",
    "Bash(*/.my.cnf*)",
    "Bash(*/.cargo/credentials*)",
    "Bash(*huggingface/token*)",
    "Bash(*ngrok.yml*)",
    "Bash(*/.vault-token*)",
    "Bash(*/.codex/auth.json*)",
    "Bash(*/.tsh*)",
    "Bash(*.ovpn*)",
    "Bash(*.jks*)",
    "Bash(*.keystore*)",

    # Commands whose job is to print a secret
    "Bash(*gh auth token*)",
    "Bash(*gcloud auth print-access-token*)",
    "Bash(*gcloud auth print-identity-token*)",
    "Bash(*az account get-access-token*)",
    "Bash(*aws sts get-session-token*)",
    "Bash(*op item get*)",
    "Bash(*op read *)",
    "Bash(*bw get password*)",
    "Bash(*bw get item*)",
    "Bash(*bw list items*)",
    "Bash(*pass show*)",
    "Bash(*secret-tool lookup*)",
    "Bash(*security find-generic-password*)",
    "Bash(*security find-internet-password*)",
    "Bash(*security dump-keychain*)",
    "Bash(*kubectl get secret*)",
    "Bash(*heroku config*)",
    "Bash(*vercel env pull*)",
    "Bash(*doppler secrets download*)",
    "Bash(*doppler secrets get*)",
    "Bash(*railway variables*)",
    "Bash(*infisical secrets*)",
    "Bash(*vault kv get*)",
    "Bash(*vault read*)",
    "Bash(*gpg --export-secret*)",

    # More history files
    "Read(~/.node_repl_history)",
    "Edit(~/.node_repl_history)",
    "Write(~/.node_repl_history)",
    "Read(~/.irb_history)",
    "Edit(~/.irb_history)",
    "Write(~/.irb_history)",
    "Read(~/.rediscli_history)",
    "Edit(~/.rediscli_history)",
    "Write(~/.rediscli_history)",
    "Read(~/.mongodb/mongosh/**)",
    "Edit(~/.mongodb/mongosh/**)",
    "Write(~/.mongodb/mongosh/**)",
    "Read(~/.lesshst)",
    "Edit(~/.lesshst)",
    "Write(~/.lesshst)",
    "Read(~/.sqlite_history)",
    "Edit(~/.sqlite_history)",
    "Write(~/.sqlite_history)",
    "Read(~/.dbshell)",
    "Edit(~/.dbshell)",
    "Write(~/.dbshell)",
    "Read(~/AppData/Roaming/Microsoft/Windows/PowerShell/PSReadLine/ConsoleHost_history.txt)",
    "Edit(~/AppData/Roaming/Microsoft/Windows/PowerShell/PSReadLine/ConsoleHost_history.txt)",
    "Write(~/AppData/Roaming/Microsoft/Windows/PowerShell/PSReadLine/ConsoleHost_history.txt)",
    "Bash(*repl_history*)",
    "Bash(*ConsoleHost_history*)",

    # macOS and Linux desktops: keychains and keyrings, browsers, messaging apps, mail
    "Read(~/Library/Keychains/**)",
    "Edit(~/Library/Keychains/**)",
    "Write(~/Library/Keychains/**)",
    "Read(~/Library/Cookies/**)",
    "Edit(~/Library/Cookies/**)",
    "Write(~/Library/Cookies/**)",
    "Read(~/Library/Application Support/Google/Chrome/**)",
    "Edit(~/Library/Application Support/Google/Chrome/**)",
    "Write(~/Library/Application Support/Google/Chrome/**)",
    "Read(~/Library/Application Support/Firefox/**)",
    "Edit(~/Library/Application Support/Firefox/**)",
    "Write(~/Library/Application Support/Firefox/**)",
    "Read(~/Library/Application Support/BraveSoftware/**)",
    "Edit(~/Library/Application Support/BraveSoftware/**)",
    "Write(~/Library/Application Support/BraveSoftware/**)",
    "Read(~/Library/Application Support/Arc/**)",
    "Edit(~/Library/Application Support/Arc/**)",
    "Write(~/Library/Application Support/Arc/**)",
    "Read(~/Library/Application Support/Microsoft Edge/**)",
    "Edit(~/Library/Application Support/Microsoft Edge/**)",
    "Write(~/Library/Application Support/Microsoft Edge/**)",
    "Read(~/Library/Application Support/1Password/**)",
    "Edit(~/Library/Application Support/1Password/**)",
    "Write(~/Library/Application Support/1Password/**)",
    "Read(~/Library/Application Support/Bitwarden/**)",
    "Edit(~/Library/Application Support/Bitwarden/**)",
    "Write(~/Library/Application Support/Bitwarden/**)",
    "Read(~/Library/Application Support/Slack/**)",
    "Edit(~/Library/Application Support/Slack/**)",
    "Write(~/Library/Application Support/Slack/**)",
    "Read(~/Library/Application Support/discord/**)",
    "Edit(~/Library/Application Support/discord/**)",
    "Write(~/Library/Application Support/discord/**)",
    "Read(~/Library/Application Support/Signal/**)",
    "Edit(~/Library/Application Support/Signal/**)",
    "Write(~/Library/Application Support/Signal/**)",
    "Read(~/Library/Messages/**)",
    "Edit(~/Library/Messages/**)",
    "Write(~/Library/Messages/**)",
    "Read(~/Library/Mail/**)",
    "Edit(~/Library/Mail/**)",
    "Write(~/Library/Mail/**)",
    "Read(~/Library/Safari/**)",
    "Edit(~/Library/Safari/**)",
    "Write(~/Library/Safari/**)",
    "Read(~/.local/share/keyrings/**)",
    "Edit(~/.local/share/keyrings/**)",
    "Write(~/.local/share/keyrings/**)",
    "Read(~/.config/Signal/**)",
    "Edit(~/.config/Signal/**)",
    "Write(~/.config/Signal/**)",
    "Read(~/.config/discord/**)",
    "Edit(~/.config/discord/**)",
    "Write(~/.config/discord/**)",
    "Read(~/.config/Slack/**)",
    "Edit(~/.config/Slack/**)",
    "Write(~/.config/Slack/**)",
    "Read(~/.thunderbird/**)",
    "Edit(~/.thunderbird/**)",
    "Write(~/.thunderbird/**)",
    "Bash(*/Library/Keychains*)",
    "Bash(*/Library/Cookies*)",
    "Bash(*/Library/Messages*)",
    "Bash(*/Library/Mail*)",
    "Bash(*share/keyrings*)",

    # Windows, best effort and untested: the credential store, browsers, password managers, messaging apps
    "Read(~/AppData/Local/Microsoft/Credentials/**)",
    "Edit(~/AppData/Local/Microsoft/Credentials/**)",
    "Write(~/AppData/Local/Microsoft/Credentials/**)",
    "Read(~/AppData/Roaming/Microsoft/Credentials/**)",
    "Edit(~/AppData/Roaming/Microsoft/Credentials/**)",
    "Write(~/AppData/Roaming/Microsoft/Credentials/**)",
    "Read(~/AppData/Roaming/Microsoft/Crypto/**)",
    "Edit(~/AppData/Roaming/Microsoft/Crypto/**)",
    "Write(~/AppData/Roaming/Microsoft/Crypto/**)",
    "Read(~/AppData/Local/Google/Chrome/User Data/**)",
    "Edit(~/AppData/Local/Google/Chrome/User Data/**)",
    "Write(~/AppData/Local/Google/Chrome/User Data/**)",
    "Read(~/AppData/Local/Microsoft/Edge/User Data/**)",
    "Edit(~/AppData/Local/Microsoft/Edge/User Data/**)",
    "Write(~/AppData/Local/Microsoft/Edge/User Data/**)",
    "Read(~/AppData/Local/BraveSoftware/**)",
    "Edit(~/AppData/Local/BraveSoftware/**)",
    "Write(~/AppData/Local/BraveSoftware/**)",
    "Read(~/AppData/Roaming/Mozilla/Firefox/**)",
    "Edit(~/AppData/Roaming/Mozilla/Firefox/**)",
    "Write(~/AppData/Roaming/Mozilla/Firefox/**)",
    "Read(~/AppData/Roaming/gcloud/**)",
    "Edit(~/AppData/Roaming/gcloud/**)",
    "Write(~/AppData/Roaming/gcloud/**)",
    "Read(~/AppData/Roaming/1Password/**)",
    "Edit(~/AppData/Roaming/1Password/**)",
    "Write(~/AppData/Roaming/1Password/**)",
    "Read(~/AppData/Roaming/Bitwarden/**)",
    "Edit(~/AppData/Roaming/Bitwarden/**)",
    "Write(~/AppData/Roaming/Bitwarden/**)",
    "Read(~/AppData/Roaming/Slack/**)",
    "Edit(~/AppData/Roaming/Slack/**)",
    "Write(~/AppData/Roaming/Slack/**)",
    "Read(~/AppData/Roaming/discord/**)",
    "Edit(~/AppData/Roaming/discord/**)",
    "Write(~/AppData/Roaming/discord/**)",
    "Read(~/AppData/Roaming/Signal/**)",
    "Edit(~/AppData/Roaming/Signal/**)",
    "Write(~/AppData/Roaming/Signal/**)",
    "Bash(*AppData/Local/Microsoft/Credentials*)",
    "Bash(*AppData/Roaming/Microsoft/Credentials*)",
    "Bash(*AppData/Roaming/Mozilla*)",
    "Bash(*AppData/Roaming/gcloud*)",
]

# Rules that earlier versions installed and that install() and remove() take out again.
RETIRED = [
    "Bash(*cat *.env*)",
    "Bash(*bat *.env*)",
    "Bash(*less *.env*)",
    "Bash(*head *.env*)",
    "Bash(*tail *.env*)",
    "Bash(*grep *.env*)",
    "Bash(*source *.env*)",
    "Bash(*. *.env*)",
]


def _read():
    try:
        return json.loads(SETTINGS_PATH.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}


def status():
    """(present, missing): the rules already in the settings file, and the ones that are not."""
    current = set((_read().get("permissions") or {}).get("deny") or [])
    present = [r for r in RULES if r in current]
    missing = [r for r in RULES if r not in current]
    return present, missing


def install():
    """Add every missing rule to the settings file. Everything else in the file is kept.
    Returns the number of rules added."""
    data = _read()
    perms = data.setdefault("permissions", {})
    deny = perms.setdefault("deny", [])
    deny[:] = [r for r in deny if r not in RETIRED]
    added = [r for r in RULES if r not in deny]
    deny.extend(added)
    SETTINGS_PATH.parent.mkdir(parents=True, exist_ok=True)
    SETTINGS_PATH.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return len(added)


def remove():
    """Take cguard's rules out of the settings file. Everything else in the file is kept.
    Returns the number of rules removed."""
    data = _read()
    perms = data.get("permissions") or {}
    deny = perms.get("deny") or []
    keep = [r for r in deny if r not in RULES and r not in RETIRED]
    removed = len(deny) - len(keep)
    if removed:
        perms["deny"] = keep
        data["permissions"] = perms
        SETTINGS_PATH.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return removed


def state():
    """on, partial or off."""
    present, missing = status()
    if not missing:
        return "on"
    return "partial" if present else "off"
